
version: '3.3'
services:

    shard1:
        container_name: shard1
        image: mongo
        command: mongod --shardsvr --replSet shard-replica --dbpath /data/db --port 27018
        ports:
            - 27018:27018
        expose:
            - '27018'
        environment:
            TERM: xterm
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ./mongo_cluster/data1:/data/db
        

    shard2:
        container_name: shard2
        image: mongo
        command: mongod --shardsvr --replSet shard-replica --dbpath /data/db --port 27018
        ports:
            - 27019:27018
        expose:
            - '27018'
        environment:
            TERM: xterm
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ./mongo_cluster/data2:/data/db
        

    shard3:
        container_name: shard3
        image: mongo
        command: mongod --shardsvr --replSet shard-replica --dbpath /data/db --port 27018
        ports:
            - 27020:27018
        expose:
            - '27018'
        environment:
            TERM: xterm
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ./mongo_cluster/data3:/data/db
        

    shard4:
        container_name: shard4
        image: mongo
        command: mongod --shardsvr --replSet shard-replica --dbpath /data/db --port 27018
        ports:
            - 27021:27018
        expose:
            - '27018'
        environment:
            TERM: xterm
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ./mongo_cluster/data4:/data/db
        

    shard5:
        container_name: shard5
        image: mongo
        command: mongod --shardsvr --replSet shard-replica --dbpath /data/db --port 27018
        ports:
            - 27022:27018
        expose:
            - '27018'
        environment:
            TERM: xterm
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ./mongo_cluster/data5:/data/db
        

    shard6:
        container_name: shard6
        image: mongo
        command: mongod --shardsvr --replSet shard-replica --dbpath /data/db --port 27018
        ports:
            - 27023:27018
        expose:
            - '27018'
        environment:
            TERM: xterm
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ./mongo_cluster/data6:/data/db
        

    shard7:
        container_name: shard7
        image: mongo
        command: mongod --shardsvr --replSet shard-replica --dbpath /data/db --port 27018
        ports:
            - 27024:27018
        expose:
            - '27018'
        environment:
            TERM: xterm
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ./mongo_cluster/data7:/data/db
        

    shard8:
        container_name: shard8
        image: mongo
        command: mongod --shardsvr --replSet shard-replica --dbpath /data/db --port 27018
        ports:
            - 27025:27018
        expose:
            - '27018'
        environment:
            TERM: xterm
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ./mongo_cluster/data8:/data/db
        

    shard9:
        container_name: shard9
        image: mongo
        command: mongod --shardsvr --replSet shard-replica --dbpath /data/db --port 27018
        ports:
            - 27026:27018
        expose:
            - '27018'
        environment:
            TERM: xterm
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ./mongo_cluster/data9:/data/db
        

    shard10:
        container_name: shard10
        image: mongo
        command: mongod --shardsvr --replSet shard-replica --dbpath /data/db --port 27018
        ports:
            - 27027:27018
        expose:
            - '27018'
        environment:
            TERM: xterm
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ./mongo_cluster/data10:/data/db
        

    shard11:
        container_name: shard11
        image: mongo
        command: mongod --shardsvr --replSet shard-replica --dbpath /data/db --port 27018
        ports:
            - 27028:27018
        expose:
            - '27018'
        environment:
            TERM: xterm
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ./mongo_cluster/data11:/data/db
        

    shard12:
        container_name: shard12
        image: mongo
        command: mongod --shardsvr --replSet shard-replica --dbpath /data/db --port 27018
        ports:
            - 27029:27018
        expose:
            - '27018'
        environment:
            TERM: xterm
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ./mongo_cluster/data12:/data/db
        

    shard13:
        container_name: shard13
        image: mongo
        command: mongod --shardsvr --replSet shard-replica --dbpath /data/db --port 27018
        ports:
            - 27030:27018
        expose:
            - '27018'
        environment:
            TERM: xterm
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ./mongo_cluster/data13:/data/db
        

    mongocfg1:
        container_name: mongocfg1
        image: mongo
        command: mongod --configsvr --replSet mongorsconf --dbpath /data/db --port 27017
        environment:
            TERM: xterm
        expose:
            - '27017'
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ./mongo_cluster/config1:/data/db
    mongocfg2:
        container_name: mongocfg2
        image: mongo
        command: mongod --configsvr --replSet mongorsconf --dbpath /data/db --port 27017
        environment:
            TERM: xterm
        expose:
            - '27017'
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ./mongo_cluster/config2:/data/db
    mongocfg3:
        container_name: mongocfg3
        image: mongo
        command: mongod --configsvr --replSet mongorsconf --dbpath /data/db --port 27017
        environment:
            TERM: xterm
        expose:
            - '27017'
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ./mongo_cluster/config3:/data/db
    mongos1:
        container_name: mongos1
        image: mongo
        depends_on:
            - mongocfg1
            - mongocfg2
            - mongocfg3
            - shard1
            - shard2
            - shard3
            - shard4
            - shard5
            - shard6
            - shard7
            - shard8
            - shard9
            - shard10
            - shard11
            - shard12
            - shard13

        command: mongos --configdb mongorsconf/mongocfg1:27017,mongocfg2:27017,mongocfg3:27017 --port 27017 --bind_ip_all
        ports:
            - 27017:27017
        expose:
            - '27017'
        volumes:
            - /etc/localtime:/etc/localtime:ro

